### ISSUE TITLE
Error handling can be improved

### ISSUE THREAD

**Issue by MadhavVij** [StellarReddit/FeedbackAWS#1]
There are many places where the code uses `log.Fatalf()` to terminate the program in case of errors. 
While this approach works well for command-line programs, it's not the best way to handle errors in an HTTP server. 

Instead, it's better to return error responses to the client and log errors to a file or a centralized logging service.

**Comment by StellarRedditApp** [comment]
Hello, @MadhavVij ! You make an excellent observation about the error handling.

This is the first lambda function we wrote for Stellar, and we followed the official Amazon AWS SDK [Go example](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/dynamo-example-create-table-item.html). 

As you can see, they utilize `log.Fatalf()` throughout the example, and in many other [examples](https://github.com/awsdocs/aws-doc-sdk-examples/tree/main/go/example_code/dynamodb). 

Calling `log.Fatalf()` will cause a 500 internal service error to be returned to the client, as well as log the data to the CloudWatch console. This warrants further investigation.

Perhaps (pseudo code):
```go
print err with fmt or log
return 500 status err
```
